CREATE TABLE `crudajax`.`abonners`
( `id` INT NOT NULL AUTO_INCREMENT , `email` VARCHAR
(255) NOT NULL , `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY
(`id`)) ENGINE = InnoDB;